const games = [
    {
        name: "Coins1",
        surname: "coins",
        desc: 'Buy virtual coins in this game',
        link: 'https://www.cyberpunk.net/',
        release: '10th of December, 2020',
        platforms: 'Playstation 4, PC, Xbox Series S/X, Playstation 5, Xbox One',
        genre: 'RPG',
        developers: 'CD PROJECT RED, CD PROJECT',
        publishers: 'CD PROJECT RED',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 78,
        id: 0,
        cover: "https://cdna.artstation.com/p/marketplace/presentation_assets/000/178/014/large/file.jpg?1563989116",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188604/cyberpunk_n6jitl.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235373/cyberpunk_1_s00vwf.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235372/cyberpunk_2_mq46xm.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235378/cyberpunk_3_fajdmi.jpg"
        ]
    },
    {
        name: "Coins2",
        surname: "coins",
        desc: 'Buy virtual coins in this game',
        link: 'https://www.cyberpunk.net/',
        release: '10th of December, 2020',
        platforms: 'Playstation 4, PC, Xbox Series S/X, Playstation 5, Xbox One',
        genre: 'RPG',
        developers: 'CD PROJECT RED, CD PROJECT',
        publishers: 'CD PROJECT RED',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 78,
        id: 1,
        cover: "https://cdna.artstation.com/p/marketplace/presentation_assets/000/178/014/large/file.jpg?1563989116",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188604/cyberpunk_n6jitl.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235373/cyberpunk_1_s00vwf.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235372/cyberpunk_2_mq46xm.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235378/cyberpunk_3_fajdmi.jpg"
        ]
    },
    {
        name: "Coins3",
        surname: "coins",
        desc: 'Buy virtual coins in this game',
        link: 'https://www.cyberpunk.net/',
        release: '10th of December, 2020',
        platforms: 'Playstation 4, PC, Xbox Series S/X, Playstation 5, Xbox One',
        genre: 'RPG',
        developers: 'CD PROJECT RED, CD PROJECT',
        publishers: 'CD PROJECT RED',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 78,
        id: 2,
        cover: "https://cdna.artstation.com/p/marketplace/presentation_assets/000/178/014/large/file.jpg?1563989116",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188604/cyberpunk_n6jitl.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235373/cyberpunk_1_s00vwf.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235372/cyberpunk_2_mq46xm.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235378/cyberpunk_3_fajdmi.jpg"
        ]
    },
    {
        name: "Coins4",
        surname: "coins",
        desc: 'Buy virtual coins in this game',
        link: 'https://www.cyberpunk.net/',
        release: '10th of December, 2020',
        platforms: 'Playstation 4, PC, Xbox Series S/X, Playstation 5, Xbox One',
        genre: 'RPG',
        developers: 'CD PROJECT RED, CD PROJECT',
        publishers: 'CD PROJECT RED',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 78,
        id: 3,
        cover: "https://cdna.artstation.com/p/marketplace/presentation_assets/000/178/014/large/file.jpg?1563989116",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188604/cyberpunk_n6jitl.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235373/cyberpunk_1_s00vwf.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235372/cyberpunk_2_mq46xm.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235378/cyberpunk_3_fajdmi.jpg"
        ]
    },
    {
        name: "Coins5",
        surname: "coins",
        desc: 'Buy virtual coins in this game',
        link: 'https://www.cyberpunk.net/',
        release: '10th of December, 2020',
        platforms: 'Playstation 4, PC, Xbox Series S/X, Playstation 5, Xbox One',
        genre: 'RPG',
        developers: 'CD PROJECT RED, CD PROJECT',
        publishers: 'CD PROJECT RED',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 78,
        id: 4,
        cover: "https://cdna.artstation.com/p/marketplace/presentation_assets/000/178/014/large/file.jpg?1563989116",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188604/cyberpunk_n6jitl.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235373/cyberpunk_1_s00vwf.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235372/cyberpunk_2_mq46xm.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235378/cyberpunk_3_fajdmi.jpg"
        ]
    },
    {
        name: "Coins6",
        surname: "coins",
        desc: 'Buy virtual coins in this game',
        link: 'https://www.cyberpunk.net/',
        release: '10th of December, 2020',
        platforms: 'Playstation 4, PC, Xbox Series S/X, Playstation 5, Xbox One',
        genre: 'RPG',
        developers: 'CD PROJECT RED, CD PROJECT',
        publishers: 'CD PROJECT RED',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 78,
        id: 5,
        cover: "https://cdna.artstation.com/p/marketplace/presentation_assets/000/178/014/large/file.jpg?1563989116",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188604/cyberpunk_n6jitl.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235373/cyberpunk_1_s00vwf.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235372/cyberpunk_2_mq46xm.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235378/cyberpunk_3_fajdmi.jpg"
        ]
    },
    {
        name: "Coins7",
        surname: "coins",
        desc: 'Buy virtual coins in this game',
        link: 'https://www.cyberpunk.net/',
        release: '10th of December, 2020',
        platforms: 'Playstation 4, PC, Xbox Series S/X, Playstation 5, Xbox One',
        genre: 'RPG',
        developers: 'CD PROJECT RED, CD PROJECT',
        publishers: 'CD PROJECT RED',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 78,
        id: 6,
        cover: "https://cdna.artstation.com/p/marketplace/presentation_assets/000/178/014/large/file.jpg?1563989116",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188604/cyberpunk_n6jitl.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235373/cyberpunk_1_s00vwf.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235372/cyberpunk_2_mq46xm.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235378/cyberpunk_3_fajdmi.jpg"
        ]
    },
    {
        name: "Coins8",
        surname: "coins",
        desc: 'Buy virtual coins in this game',
        link: 'https://www.cyberpunk.net/',
        release: '10th of December, 2020',
        platforms: 'Playstation 4, PC, Xbox Series S/X, Playstation 5, Xbox One',
        genre: 'RPG',
        developers: 'CD PROJECT RED, CD PROJECT',
        publishers: 'CD PROJECT RED',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 78,
        id: 7,
        cover: "https://cdna.artstation.com/p/marketplace/presentation_assets/000/178/014/large/file.jpg?1563989116",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188604/cyberpunk_n6jitl.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235373/cyberpunk_1_s00vwf.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235372/cyberpunk_2_mq46xm.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235378/cyberpunk_3_fajdmi.jpg"
        ]
    },
    {
        name: "Coins9",
        surname: "coins",
        desc: 'Buy virtual coins in this game',
        link: 'https://www.cyberpunk.net/',
        release: '10th of December, 2020',
        platforms: 'Playstation 4, PC, Xbox Series S/X, Playstation 5, Xbox One',
        genre: 'RPG',
        developers: 'CD PROJECT RED, CD PROJECT',
        publishers: 'CD PROJECT RED',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 78,
        id: 8,
        cover: "https://cdna.artstation.com/p/marketplace/presentation_assets/000/178/014/large/file.jpg?1563989116",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188604/cyberpunk_n6jitl.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235373/cyberpunk_1_s00vwf.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235372/cyberpunk_2_mq46xm.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235378/cyberpunk_3_fajdmi.jpg"
        ]
    },
    {
        name: "Coins10",
        surname: "coins",
        desc: 'Buy virtual coins in this game',
        link: 'https://www.cyberpunk.net/',
        release: '10th of December, 2020',
        platforms: 'Playstation 4, PC, Xbox Series S/X, Playstation 5, Xbox One',
        genre: 'RPG',
        developers: 'CD PROJECT RED, CD PROJECT',
        publishers: 'CD PROJECT RED',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 78,
        id: 9,
        cover: "https://cdna.artstation.com/p/marketplace/presentation_assets/000/178/014/large/file.jpg?1563989116",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188604/cyberpunk_n6jitl.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235373/cyberpunk_1_s00vwf.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235372/cyberpunk_2_mq46xm.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235378/cyberpunk_3_fajdmi.jpg"
        ]
    },
    {
        name: "Coins11",
        surname: "coins",
        desc: 'Buy virtual coins in this game',
        link: 'https://www.cyberpunk.net/',
        release: '10th of December, 2020',
        platforms: 'Playstation 4, PC, Xbox Series S/X, Playstation 5, Xbox One',
        genre: 'RPG',
        developers: 'CD PROJECT RED, CD PROJECT',
        publishers: 'CD PROJECT RED',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 78,
        id: 10,
        cover: "https://cdna.artstation.com/p/marketplace/presentation_assets/000/178/014/large/file.jpg?1563989116",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188604/cyberpunk_n6jitl.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235373/cyberpunk_1_s00vwf.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235372/cyberpunk_2_mq46xm.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235378/cyberpunk_3_fajdmi.jpg"
        ]
    },
    {
        name: "Coins12",
        surname: "coins",
        desc: 'Buy virtual coins in this game',
        link: 'https://www.cyberpunk.net/',
        release: '10th of December, 2020',
        platforms: 'Playstation 4, PC, Xbox Series S/X, Playstation 5, Xbox One',
        genre: 'RPG',
        developers: 'CD PROJECT RED, CD PROJECT',
        publishers: 'CD PROJECT RED',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 78,
        id: 11,
        cover: "https://cdna.artstation.com/p/marketplace/presentation_assets/000/178/014/large/file.jpg?1563989116",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188604/cyberpunk_n6jitl.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235373/cyberpunk_1_s00vwf.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235372/cyberpunk_2_mq46xm.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235378/cyberpunk_3_fajdmi.jpg"
        ]
    },
    {
        name: "Coins13",
        surname: "coins",
        desc: 'Buy virtual coins in this game',
        link: 'https://www.cyberpunk.net/',
        release: '10th of December, 2020',
        platforms: 'Playstation 4, PC, Xbox Series S/X, Playstation 5, Xbox One',
        genre: 'RPG',
        developers: 'CD PROJECT RED, CD PROJECT',
        publishers: 'CD PROJECT RED',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 78,
        id: 12,
        cover: "https://cdna.artstation.com/p/marketplace/presentation_assets/000/178/014/large/file.jpg?1563989116",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188604/cyberpunk_n6jitl.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235373/cyberpunk_1_s00vwf.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235372/cyberpunk_2_mq46xm.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235378/cyberpunk_3_fajdmi.jpg"
        ]
    },
]

export default games;
